on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: yarn
    - run: tsc
    - run: yarn vite build --base=spa--mit-reveal.js/
    - run: rm -rf docs
    - run: mv dist docs
    - run: git add docs
    - run: git config --global user.name 'Github Action'
    - run: git config --global user.email 'github@action.noreply.github.com'
    - run: git commit -m "Update docs"
    - run: git push origin main
